name: Compile and Test Stages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:latest
    steps:
    - uses: actions/checkout@v3  
    - name: Compile Code
      run: make compile -j SkipVerify=1

    - name: Run UnitTests
      run: make test
