name: Compile and Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:latest
    steps:
    - uses: actions/checkout@v4  
    - name: Compile Code
      run: make compile -j SkipVerify=1

    - name: Run UnitTests
      run: make test SkipVerify=1
