name: Documentation

on: 
    release: 
        types: [published]

jobs:
    generate_and_publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: sudo apt install -y doxygen graphviz

            - name: Generate Documentation
              run: make doc

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./target/doc/irioCore/html
                full_commit_message: Generated documentation for ${{ github.ref }}
