name: Generate Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  PACKAGE_DIR: "target/packages/x86_64"

jobs:
  Sonar:
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  package:
    needs: Sonar
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:v1.0
    steps:
    - name: Install alien
      run: |
        dnf config-manager --set-enabled crb
        dnf install -y alien

    - uses: actions/checkout@v3  
    - name: Generate RPM packages
      run: | 
        make package -j

    - name: Generate DEB packages
      working-directory: env.PACKAGE_DIR
      run: |
        alien *.rpm
    
    - name: Group packages
      working-directory: env.PACKAGE_DIR
      run: |
        tar -czvf rpm-irioCore-${{ github.ref_name}}.tar.gz *.rpm
        tar -czvf deb-irioCore-${{ github.ref_name}}.tar.gz *.deb

    - name: Generate release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.PACKAGE_DIR }}/*.tar.gz

  Documentation:
    uses: ./.github/workflows/doc.yml
    secrets: inherit
    needs: package
