name: Generate Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  PACKAGE_DIR: "target/packages/x86_64"

jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Check Makefile version matches tag
      run: |
        # Extract version from Makefile
        MAKEFILE_VERSION=$(grep -oP 'VERSION=\K.*' Makefile)
        # Extract version from GitHub tag, removing the 'v' prefix
        GITHUB_VERSION=${GITHUB_REF/refs\/tags\/v/}
        # Compare versions
        if [ "$MAKEFILE_VERSION" != "$GITHUB_VERSION" ]; then
          echo "Error: Version in Makefile ($MAKEFILE_VERSION) does not match GitHub tag ($GITHUB_VERSION)"
          exit 1
        fi

  Sonar:
    needs: CheckVersion
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  
  package:
    needs: Sonar
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:latest
    steps:
    - uses: actions/checkout@v4  
    - name: Generate RPM packages
      run: | 
        make package -j

    - name: Generate DEB packages
      working-directory: ${{ env.PACKAGE_DIR }}
      run: |
        alien *.rpm
    
    - name: Group packages
      working-directory: ${{ env.PACKAGE_DIR }}
      run: |
        tar -czvf rpm-irioCore-${{ github.ref_name}}.tar.gz *.rpm
        tar -czvf deb-irioCore-${{ github.ref_name}}.tar.gz *.deb

    - name: Generate release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.PACKAGE_DIR }}/*.tar.gz

  Documentation:
    uses: ./.github/workflows/doc.yml
    secrets: inherit
    needs: package
