name: Run UnitTests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:latest
    steps:    
    - uses: ./.github/workflows/compile.yml  
    - name: Run UnitTests
      run: make test SkipVerify=1
