name: Run UnitTests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  runUnitTests:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:latest
      
    steps:
    - uses: actions/checkout@v4      
    - name: Run UnitTests
      run: make test SkipVerify=1
